### ISSUE TITLE
Need review on fixNetworkingHeadings function

### ISSUE THREAD

**Issue by rlambert27** [pheedloop/cca2022-customscript#15]
I'm getting the impression that this isn't working because the jQuery script has already run when we click on the "Groups" link in Networking (https://pheedloop.com/CCA2022/virtual/?page=attendees&section=ATT4T6CEIB0FE728FJZ3K2ZFTABX#). 

Once on the Networking page, click on "Groups", then click on "1. Mental Health Community. French/LSQ (10:45 - 11:45 am ET)".

New content appears on the right asking you to set your device permissions. Currently Pheedloop has indicated that there is no way to translate the new updated content.

This is affecting two functions

- fixNetworkingHeadings
- fixNetworkDeviceTranslations

The fixNetworkingHeadings() is not updating the topic to an H1 and the fixNetworkDeviceTranslations() is not fixing the French "Device settings" phrase.

The function fixNetworkDeviceTranslations() lays the groundwork to fix the heading and translations but it's not quite working. We'll need to somehow update the jQuery to "listen" for the click on the event I believe before we can update the heading and translations.

**Comment by andrewnordlund** [comment]
I'm thinking because everything in the main section is in an `<iframe>`.

So, it seems as though we either need to get JQuery to reach into an iFrame to make changes there; or insert a JQuery script into the frame and get it to make changes.

**Comment by andrewnordlund** [comment]
Having looked over your code, really don't know why it's not working.  It looks like it _should_work.  In fact, `fixNetworkingHeadings()` isn't even in an `<iframe>`.

The only things I can think of is that these functions aren't being called at the right time/event.  It seems they're being called from `fixNetworkingPage()` which is being called from `letErRip()` which is being called shortly after page load, or clicking on a left-nav button.

Really, these shouldn't be called until someone clicks a session box after clicking "Groups" on the Network page.

**Comment by andrewnordlund** [comment]
For some reason I can't seem to reach down into the `<iframe>` with JQuery.  There's gotta be a way, but right now we're just going to lower this on the priority list.

If anyone knows how to do this easy peasy, go ahead and take it.

**Comment by rlambert27** [comment]
Closing this as I provided screenshots of the translation if any users require the translations.
