### ISSUE TITLE
Account - Visible focus indicator

### ISSUE THREAD

**Issue by rlambert27** [pheedloop/cca2022-customscript#19]
Not showing up on the toggles.

**Comment by rlambert27** [comment]
Working on this.

**Comment by andrewnordlund** [comment]
Ughhhhh

For some reason, now that the code has been committed, the sliders are now mouse-accessible, but not keyboard accessible.  I'll work on this.

**Comment by rlambert27** [comment]
Fixed via commit 990beda3d4c23bc9f3a72e0e1eb90561a1edf7f8
