### ISSUE TITLE
Program EN and FR - Issue with + and checkmark icon

### ISSUE THREAD

**Issue by rlambert27** [pheedloop/cca2022-customscript#25]
In commit 28f13d5d4919d919b57aeb7de302e4aa39738c74 i'm adding an accessible name on the + icon. I realize after though that when the checkmark is displayed it's still got the same label, no indicate that it has been added to your calendar (I don't know where the calendar is, we'll need to check with Marco).

I have to leave shortly so adding this as an issue as we may want to update <span> to say the course is in the calendar.

**Comment by rlambert27** [comment]
So the ability to see items you've add is in the filter option. 

Also we need to increase the click size on the +/checkmark icon.

**Comment by andrewnordlund** [comment]
Something interesting is happening....

If you click the checkbox/+ icon with your mouse, that session gets added to/removed from your schedule.

But if you _tab_ to it and hit Space, your screen scrolls.  If you hit Enter, then that session opens up in the right pane; as though you clicked on that session, but not in the checkbox.

Under WCAG 4.1.2, Name, Role, Value; as it stands, it has a name, and I've added a value (or state, which is implied by either "Add to Personal Schedule" or "Remove from Personal Schedule".  But it lacks a role.

I'm thinking if I make it a `<button >` then one may be able to activate it with their keyboard to add/remove it from their personal schedule, but not open it up in the side panel.

**Comment by rlambert27** [comment]
Fixed via commit 0d6f1682cda0b7f71f8ed2b106c4b95892e45939
