### ISSUE TITLE
Priority - Settings focus on the right

### ISSUE THREAD

**Issue by rlambert27** [pheedloop/cca2022-customscript#47]
For any page that has a list of selections on the left and that then updates the content on the right. Should we move the keyboard focus to the new content when something is selected?

@andrewnordlund - I think this might be an important fix we could work on.

**Comment by andrewnordlund** [comment]
Good idea.  But i'd like to see a site-wide consistent solution.

Should we throw a `tabindex=-1` on the `<h1>`s we're injecting, and throw focus to that?

**Comment by andrewnordlund** [comment]
Or the `<div id="page">` element?

Put something in `fixAllPages()`?

**Comment by rlambert27** [comment]
Not the `<div id="page">` since that holds both the left/right panes. I guess we could put an ID on the `<h1>` since we seem to have done that on all pages.

However we would still need to implement a click listener for each page wouldn't we? If we do that then each page has an ID on the right pane that we could throw the focus on.

**Comment by andrewnordlund** [comment]
Is there an `<h1>` on Career Fair?  I'm not seeing one - until you select an employer and their info loads.

I'm not seeing an `<h1>` on Showcase either.

**Comment by rlambert27** [comment]
Yeah so on the Showcase the H1 is the first company name that loads.

On Career Fair you are correct there is no H1 until you select an item from the left pane, then the company name is the H1.
