### ISSUE TITLE
Bug with filter dropdown

### ISSUE THREAD

**Issue by rlambert27** [pheedloop/cca2022-customscript#55]
The dropdown is shifting left when content is too wide.

**Comment by andrewnordlund** [comment]
To reproduce:
1. Go to Main Stage (FR)
2. Open Filter

You see this:
![image](https://user-images.githubusercontent.com/1805963/170371565-7ca0b46f-d62e-4af8-bd06-b9008b8b299e.png)

**Comment by andrewnordlund** [comment]
From what I can see, `<div class="dropdown-menu show" style="max-height: 405.8px; overflow: hidden; min-height: 162px; position: absolute; transform: translate3d(*-410px*, 42px, 0px); top: 0px; left: 0px; will-change: transform;" x-placement="bottom-start">`

Why is this transforming 410px to the left?

In an earlier fix to get rid of whitespace in Chrome, I had to put `overflow-y:hidden;` on `/html/body/div[2]/div[2]/div[1]/div/div/div[1]`

If I remove that, then this drop-down doesn't shift to the left.

But if I don't, then we get whitespace in Chrome.

Why on Earth does stopping vertical overflow cause this issue?!

**Comment by andrewnordlund** [comment]
changing `overflow-y: hidden;` to `overflow-y:clip;` seems to do the trick in my browsers.

PR submitted.  Now wait to see it in prod.
